### ISSUE TITLE
Slack attachments, buttons & menus

### ISSUE THREAD

**Issue by CentaurWarchief** [Yoctol/bottender#24]
Heyo! 

I was wondering how I'd send custom attachments to Slack through the `context`. I would love some API that allows me to reach `postMessage` directly. 

Also, do you guys have any idea on how to integrate with Slack callbacks? Let's say that I want to send a message with a button that does something.

**Comment by tw0517tw** [comment]
Hi @CentaurWarchief !

Actually there is already `context.postMessage()` at [here](https://github.com/Yoctol/bottender/blob/master/src/context/SlackContext.js#L47-L61) but we didn't pass in the third argument for the underlying `messaging-api-slack`. The support of sending buttons can be easily achieved by pass in third argument, with maybe automatically stringify the `attachment` field or you have to manually do it as Slack need it to be a string. We can shortly made a patch for these.

For handling button callbacks, it's a bit more complicated since Slack send the button callbacks in an `application/x-www-form-urlencoded` request and the payload is a JSON string which is a lot different from the Events API. We need to change the server part and the request handling part to support this.

**Comment by CentaurWarchief** [comment]
The problem is that sometimes I don't have `text`. Just `attachments`. Not sure I can send `text: undefined` to skip the field and therefore, skip the validation: https://github.com/Yoctol/messaging-apis/blob/master/packages/messaging-api-slack/src/SlackOAuthClient.js#L241

What I would do is: `context.postMessage({ text })` or `context.postMessage({ attachments: [] })`. But I am not sure if this breaks any interface. The `channelId` would be implicitly set.

So, in regards to button callbacks and menus, isn't there any way I can catch those events and handle 'em myself? Doesn't need to be a custom bot API.

**Comment by tw0517tw** [comment]
Ah, I missed that `text` is not required if only `attachments` is provided. I guess we'll need a modification to the arguments of `postMessage` for it to receive only `attachments`. (following in https://github.com/Yoctol/messaging-apis/issues/211)

For now (bottender@0.14.5), you may try
```js
context.postMessage('text')
context.sendText('text')
```
or
```js
context.postMessage(undefined, { attachments: [] })
```
, though I'm not sure how Slack server handles the no-text-requests.

For the button callbacks, you can just setup another server or another route in current server that accepts `application/x-www-form-urlencoded` request and handle it by yourself, then setup your Slack app's `Interactive Components` request URL to the new server/route.
But I think it should be handled as an `SlackEvent` so the bot logic can be integrated and I'm figuring it out now.

**Comment by CentaurWarchief** [comment]
@tw0517tw that would be niiceee. Maybe, for now, we can just wrap it into a `SlackEvent` with some response handlers

**Comment by tw0517tw** [comment]
published!
