### ISSUE TITLE
[Question] - Store context in memory for async funcion

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#355]
Hi,

My solution was working on Bottender 0.14.39 but now stop working.

Using Facebook Messenger for getting input values from WebView. My process was:

1 - Store context, conversationId in memory

```javascript
    FormData.set(id, {item: item, context: context, time: new Date()});
```

2 - Show to user WebView

3 - When user responses the webview, feching by id i was getting the context then send a text.
```javascript
server.post('/setForm/:formId', async function (req, res, obj) {
        let body = req.body;
        let form = FormData.get(req.params.formId);

        console.log(body);

        let payload = FacebookUiBuilder.buildPayload(body.dialog, "", JSON.stringify(body.data));

        await form.context.sendText(buildText(body.data.formData));
        console.log(payload);
        AsksuiteBotTenderConversation.executeAction(form.context, payload,  AskSuiteMessageResolver);

        res.send({"ok": "ok"})
    });
```

It was working, but after upgrading to Bottender 0.15.10 i'm getting this error:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot set property listening of #<Server> which has only a getter 

```

Is there a way to store it? Or to find contexts by id? Or any other solution?

Thanks

**Comment by chentsulin** [comment]
`context.sendText` should only be called in the particular context to handle received messenger event.

If you want to push messages to the user when your API be called, you should call [`client.sendText(userId, text)`](https://github.com/Yoctol/messaging-apis/tree/master/packages/messaging-api-messenger#sendtextuserid-text--options) instead.

You should save userId instead of the whole context.

```js
const db = {};

db[id] = {item: item, userId: context.session.user.id, time: new Date()};
```

You can get your messenger client via `bot.connector.client`. 

```js
server.post('/setForm/:formId', async function (req, res, next) {
  let body = req.body;
  let form = db[req.params.formId];

  await bot.connector.client.sendText(form.userId, 'hello world');
  
  res.send({"ok": "ok"})
});
```

Saving data in memory may be lost when your server crash or restart, so It's better to save them to your own persistent database.

**Comment by pavei** [comment]
yep! It was solved! Thanks
