### ISSUE TITLE
[Question] - Handover control to User and show a message

### ISSUE THREAD

**Issue by pavei** [Yoctol/bottender#356]
Hi,

In facebook messenger i give the power of  "stoping" the bot to the Inbox. So, to do this i treat all echo messages to find this comands like "stop", "continue". It was working, on old version of bottender. But now on new version there is a code block that not let me advise the user that the bot was stopped or continued.

So, is there a way to send a message to user, that chatbot is stopped when Inbox send a command? 

Code block on https://github.com/Yoctol/bottender/blob/36981aa7b4fb2690f136b5dbaa50c3cab0ff5c03/src/context/MessengerContext.js#L98

```javascript
 if (this._event.isEcho || this._event.isDelivery || this._event.isRead) {
      warning(
        false,
        'sendText: calling Send APIs in `message_reads`(event.isRead), `message_deliveries`(event.isDelivery) or `message_echoes`(event.isEcho) events may cause endless self-responding, so they are ignored by default.\nYou may like to turn off subscription of those events or handle them without Send APIs.'
      );
      return;
```

My Code
```javascript
  if (context.event.isEcho && context.event.isText) {
            console.log("echo", context.event.text);

            let instructions = ["stop"]
            let instructionsSuccess = ["continue"];

            let text = context.event.text.toLowerCase().trim();

            if (instructions.indexOf(text) >= 0) {

                console.log("stop");
                await context.passThreadControlToPageInbox();
                await context.sendText("The chatbot has been stopped")

            } else if (instructionsSuccess.indexOf(text) >= 0) {

                 console.log("back")
                await context.takeThreadControl();
                await context.sendText("🤖 Chatbot is ready!")
              
            }
```

**Comment by Calvin-Lin** [comment]
You can use the `Move to Main` and `Mark as done` buttons of Messenger platform to control your bot manually, instead of listening to echo event.

![2018-11-06 4 29 49](https://user-images.githubusercontent.com/1947599/48051864-449f9380-e1e1-11e8-8885-84a7f0905f70.png)
![2018-11-06 4 30 02](https://user-images.githubusercontent.com/1947599/48051867-46695700-e1e1-11e8-9a43-73efbfa40f1a.png)

To use this, you need to assign app roles first:
https://developers.facebook.com/docs/messenger-platform/handover-protocol/assign-app-roles

Let your bot app be `Primary Receiver`, and let the inbox be `Secondary Receiver`.

After the roles be assigned, your users will be in `Done` when they interact with your bot.

When you press the `Move to Main` button, the inbox will send a `request_thread_control` event to your bot, and move user form `Done` to `Main`, then you can do

```
await context.passThreadControlToPageInbox();
await context.sendText("The chatbot has been stopped")
```

When you press the `Mark as done` button, the inbox will send a `pass_thread_control` event to your bot, and move user form `Main` to `Done`, then you can do

```
await context.sendText("🤖 Chatbot is ready!")
```

You don't need to call `context.takeThreadControl()` in this scenario, because the inbox has already pass thread control back to your bot.

**Comment by chentsulin** [comment]
Hi @pavei, 
It seems that @Calvin-Lin has already provided a great answer, so I'm going to close this.
