### ISSUE TITLE
resetState without receiving context

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/bottender#392]
Hello, I would like to know is there any way to resetState without receiving context.
For example, I would like to reset order state after receiving Line Pay webhook success callback.
Thanks.

**Comment by wtflink** [comment]
If you must do it this way, we store state in sessions, which you can use some low level API to manipulate it. 

If you can find the sesison and do what we do in the resetState function as below:
https://github.com/Yoctol/bottender/blob/36ab5342f6fc2df8adf476c6007f75ef051a8747/src/context/Context.js#L155-L170
That might work, but we suggest you deal the payment or order info more careful and store it into other reliable storage rather than the session.

**Comment by yusef-ho** [comment]
@wtflink 
Thanks.
currently, we only store orderId and invoiceId in state, and use Ids to call our backend API to fetch data to generate Flex message , but we would like to wipe state after we received the webhook from Line Pay in order to start another new service for customer.
Is there any way we can achieve this??

**Comment by chentsulin** [comment]
Hi @yusef-ho, I'd say you should store your `orderId` and `invoiceId` in your own database, not in the session stores, if you want to access them outside of the conversation. Just like if want to share something between your bot and your webpage.
