### ISSUE TITLE
version issue messaging-api-messenger 

### ISSUE THREAD

**Issue by manojskills** [Yoctol/bottender#420]
Warning: getUserProfile() failed, `session.user` will only have `id`
Error: Messenger API - 32 OAuthException (#32) Page request limit reached
  at handleError (/data/nodejs/coke_bot/node_modules/bottender/node_modules/messaging-api-messenger/lib/MessengerClient.js:96:9)
   at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:189:7)
 Error Message -
  Messenger API - 32 OAuthException (#32) Page request limit reached
 Request -
 GET https://graph.facebook.com/v2.11/2796691377012814?access_token=xxxx|coke_bo | Response -
  400 Bad Request
Please you update lastest  version of  messaging-api-messenger  
https://graph.facebook.com/v3.3/2796691377012814?access_token

**Comment by chentsulin** [comment]
Hi @manojskills, the error message (`Page request limit reached`) shows that your page reached the request limit in that period. Have you ever do anything frequently in that period? 

Are there any reproduce steps for this issue? It's uncommon to reach the request limit just because of `getUserProfile`.
It seems to me that it's not an issue for the version of `of messaging-api-messenger`. What do you think?

**Comment by chentsulin** [comment]
Merge into #424
