### ISSUE TITLE
how to deploy to ZEIT Now with npm start

### ISSUE THREAD

**Issue by hilezi** [Yoctol/bottender#620]
Hi guys, I am FrontEnd developer and I am alone, I am not good in BackEnd at now

everything is very smooth on local development (many thanks you made smooth docs), but not with deployment

I am following [docs/deployment#now], but seems not smooth/clarity for me

One week has passed and I still don't understand how to.

I know this question may not is bottender 's responsibility, I am also checking ZEIT Now 's docs and googling about ZEIT Now

may I ask some little hint?

anyway, finally, the ZEIT Now 's build process is pretty good, but don't know how to make ZEIT Now go with `npm start` and listen port 5000

```
// now.json
{
  "build": {
    "env": {
      "LINE_ACCESS_TOKEN": "@line_access_token",
      "LINE_CHANNEL_SECRET": "@line_channel_secret"
    }
  }
}
```

and

```
$now secrets list
> 2 secrets found under lezi [532ms]

  name                 created
  line_access_token    8h ago
  line_channel_secret  8h ago
```

and 

```
// package.json
  "scripts": {
    "predev": "npm run build:src",
    "dev": "concurrently --names 'ts,bot' 'npm run build:src -- --watch' 'bottender dev'",
    "build": "npm run build:src",
    "build:src": "TS_NODE_PROJECT=\"tsconfig-webpack.json\" webpack",
    "lint": "eslint .",
    "start": "bottender start",
    "test": "jest"
  },
```

then 

```
now --prod
```

[docs/deployment#now]: https://bottender.js.org/docs/deployment#now

**Comment by chentsulin** [comment]
Hi @hilezi, the doc you read was written for Now v1. Bottender team is writing the new deployment doc and still a WIP.

I have some tips to help you figure out how to deploy your app with Now v2.

First of all, Now 2.0 doesn't support npm scripts, so we need a `server.js` as entry point: (See https://github.com/Yoctol/bottender/tree/master/examples/custom-server-express as example)

`server.js`:

```js
const bodyParser = require('body-parser');
const express = require('express');
const { bottender } = require('bottender');

const app = bottender({
  dev: process.env.NODE_ENV !== 'production',
});

const port = Number(process.env.PORT) || 5000;

const handle = app.getRequestHandler();

app.prepare().then(() => {
  const server = express();

  server.use(
    bodyParser.json({
      verify: (req, _, buf) => {
        req.rawBody = buf.toString();
      },
    })
  );

  server.all('*', (req, res) => {
    return handle(req, res);
  });

  server.listen(port, err => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${port}`);
  });
});
```

In `now.json`:

- version should be `2`
- use `@now/node` to bundle `server.js` 
- put `bottender.config.js` and `index.js` into `includeFiles` (now uses ncc and webpack bundler under the hood, so we need to tell them to put those two files into the bundle)
- route all (`/.*`) to `server.js`
- add envs to `env`

```json
{
  "version": 2,
  "builds": [
    { 
      "src": "server.js", 
      "use": "@now/node",
      "config": {
        "includeFiles": [
          "bottender.config.js",
          "index.js"
        ],
        "bundle": true
      }
    }
  ],
  "routes": [{
    "src": "/.*",
    "dest": "/server.js"
  }],
  "env": {
    "LINE_ACCESS_TOKEN": "@line_access_token",
    "LINE_CHANNEL_SECRET": "@line_channel_secret",
    "DEBUG": "bottender*,messaging-api*"
  }
}
```

(if you are debugging your app, you may set DEBUG env to `bottender*,messaging-api*`)

In `bottender.config.js`, you **must** configure those channels with `sync: true` (execute in sync mode), because serverless function cannot call APIs to Messenger, LINE,... after HTTP response is sent or the function has been terminated.

```js
module.exports = {
  // ... skip
  channels: {
    messenger: {
      enabled: true,
      sync: true,
      // ...skip
    },
    line: {
      enabled: true,
      sync: true,
      // ...skip
    },
    telegram: {
      enabled: false,
      sync: true,
      // ...skip
    },
    slack: {
      enabled: false,
      sync: true,
      // ...skip
    },
    viber: {
      enabled: false,
      sync: true,
      // ...skip
    },
  },
};
```

Besides, I got an error when no **engines** setting in `package.json`, so I'd like to mention this line:

```json
{
  // skip...
  "engines": { "node": "12.x" }
}
```

**Comment by chentsulin** [comment]
Hi @hilezi, we just published the new deployment guide to our website!
https://bottender.js.org/docs/advanced-guides-deployment
Special thanks to @qshiwu
