### ISSUE TITLE
Not working when verifying webhook URL on LINE platform

### ISSUE THREAD

**Issue by wingliu0** [Yoctol/bottender#96]
Version of Bottender: ```"bottender": "^0.14.3",```
Steps to reproduce:
1.  start the server with any endpoint eg: 
```const server = createServer(bot, { path: '/webhook' });```
2. press the Verify on https://developers.line.me/console after changed a new webhook URL
3. a mock message will be sent from LINE to our server, and it will be something like this eg: 
```{
    "events": [
        {
            "replyToken": "00000000000000000000000000000000",
            "type": "message",
            "timestamp": 1512777897980,
            "source": {
                "type": "user",
                "userId": "Udeadbeefdeadbeefdeadbeefdeadbeef"
            },
            "message": {
                "id": "100001",
                "type": "text",
                "text": "Hello, world"
            }
        },
        {
            "replyToken": "ffffffffffffffffffffffffffffffff",
            "type": "message",
            "timestamp": 1512777897980,
            "source": {
                "type": "user",
                "userId": "Udeadbeefdeadbeefdeadbeefdeadbeef"
            },
            "message": {
                "id": "100002",
                "type": "sticker",
                "packageId": "1",
                "stickerId": "1"
            }
        }
    ]
}

```

4. ```internal/process/warning.js:18 (node:16291) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: LINE API - Not found```
this error will be logged, and it is due to the unhandled promise rejection in `lib/express/createMiddleware.js:12`

Is this a bug or a behavior? If it is a behavior, how can I handle the promise rejection?

**Comment by tw0517tw** [comment]
Hi @wingliu0,

Thanks for reporting. That unhandled rejection happens because bottender will try to retrieve user info from LINE with the fake user ID from this verifying request and that would fail. We should ignore these events to fix this.

You can just ignore it for now as the webhook is still set.

**Comment by wingliu0** [comment]
Hi,
but i cant ignore that. cus it leads to the fail verification on LINE

2017年12月9日 12:23，"吳東曄 Wu, Dung-Ie" <notifications@github.com>寫道：

**Comment by tw0517tw** [comment]
@wingliu0 ,

The verification will fail, but webhook is still setup well and you will start receive events from LINE.

We will work on making that verification succeed. But before the patch been released, you can still run your bot (yes, with the failed webhook verification).

**Comment by wingliu0** [comment]
@tw0517tw ,
But this means I cant deploy it to AWS elastic beantalk nor google app engine nor heroku

**Comment by tw0517tw** [comment]
Hi @wingliu0 ,

I'm not so familiar to AWS and GAE, but I've successfully deployed a LINE bot to Heroku with verification failing version of bottender. It'll be good if you can provide more information on why it can't be done.

In fact, you can just **update** the webhook URL, enter whatever you get from AWS or GAE or Heroku, but completely **skip verifying** on LINE developers site channel settings. That's why I said you can ignore the verification failure error.

**Comment by wingliu0** [comment]
@tw0517tw 
oh really?! I thought the verification is a must

**Comment by tw0517tw** [comment]
bottender@0.14.10 has been released, it can handle LINE webhook verify requests now!
